journaling_prompts = [
    "What are three things you are grateful for today?",
    "How did you feel when you woke up this morning?",
    "Describe a recent situation that made you happy.",
    "What are your top three values in life?",
    "How have you grown in the past year?",
    "What fears are holding you back?",
    "Describe your ideal day.",
    "How do you react to stress, and why?",
    "What are your strengths and weaknesses?",
    "How do you want to be remembered?",
    "What emotion did you feel most strongly today?",
    "When do you feel most at peace?",
    "Write about a recent moment of frustration and what caused it.",
    "What do you do to calm yourself when anxious?",
    "How do you express anger in a healthy way?",
    "Describe a time you felt truly understood.",
    "When was the last time you cried, and why?",
    "What triggers your happiest memories?",
    "How do you know when you're stressed?",
    "What helps you release negative emotions?",
    "What are your short-term goals for this month?",
    "What are your long-term life goals?",
    "How do you measure success?",
    "Describe a goal you achieved and how it felt.",
    "What motivates you when you feel stuck?",
    "What habit would you like to build this year?",
    "List three small wins from the past week.",
    "What's holding you back from your dreams?",
    "How do you stay focused when life gets busy?",
    "What would you attempt if you knew you could not fail?",
    "Describe your surroundings in detail right now.",
    "What did you notice today that you usually overlook?",
    "How does your body feel at this moment?",
    "Name five things you can hear, see, and smell right now.",
    "What thoughts keep recurring in your mind lately?",
    "How do you practice self-care daily?",
    "Write about a moment when you felt fully present.",
    "What does calm feel like to you?",
    "How often do you compare yourself to others?",
    "What rituals make you feel grounded?",
    "Describe a perfect imaginary world.",
    "Write a short story about your future self.",
    "Invent a new holiday and its traditions.",
    "What superpower would you choose, and why?",
    "Imagine your life five years from now.",
    "Write a letter to your past self.",
    "Write a letter to your future self.",
    "Describe a character who is the opposite of you.",
    "Invent a product that would make life easier.",
    "Create a fictional dialogue between your inner critic and inner cheerleader.",
    "Who inspires you the most, and why?",
    "Describe your ideal friend.",
    "How do you nurture your relationships?",
    "Write about someone you need to forgive.",
    "Describe a meaningful conversation you had recently.",
    "How do you express love to others?",
    "Who do you feel most comfortable around, and why?",
    "How do you handle conflict in relationships?",
    "Write about a friendship that changed you.",
    "How do you want your relationships to evolve?",
    "Write about a place that feels like home.",
    "Describe your favorite childhood memory.",
    "What is your happiest memory?",
    "What's a lesson you learned the hard way?",
    "Describe a time you took a risk.",
    "Write about an experience that changed your perspective.",
    "What's a recent adventure you went on?",
    "Describe a day that didn't go as planned.",
    "Write about a mistake you're glad you made.",
    "What's a tradition you cherish?",
    "What's a skill you want to learn?",
    "What did you learn about yourself recently?",
    "How do you overcome challenges?",
    "Write about a book, movie, or quote that impacted you.",
    "Describe a mentor or teacher who influenced you.",
    "What have you unlearned over the years?",
    "Write about a fear you've conquered.",
    "How do you handle constructive criticism?",
    "What does personal growth mean to you?",
    "How do you celebrate your progress?",
    "What does happiness mean to you?",
    "How do you define success?",
    "What is the meaning of life, in your opinion?",
    "Do you believe in fate or free will?",
    "What is your personal philosophy?",
    "How do you deal with uncertainty?",
    "What is beauty to you?",
    "How do you measure time in your life?",
    "What is one belief you have changed?",
    "How do you want to contribute to the world?",
    "What makes you laugh the most?",
    "Write about your favorite food and why you love it.",
    "Describe your dream vacation.",
    "Write a list of silly goals you'd like to try.",
    "What's your favorite way to spend a rainy day?",
    "Describe your ideal weekend.",
    "If you could have any animal as a pet, which would you choose?",
    "Write a list of songs that define your life.",
    "Describe a perfect, lazy morning.",
    "Create a “bucket list” of small joys you want to experience."
]
